### ISSUE TITLE
REQ: Properties - Configure dm3 profile with better UX

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#1127]
## Current behavior

We have the dialog to add dm3 names (with the selection if dm3 cloud or optimism is the location) and to publish it on a ens or genome name (also a selection). This is too complex and bad UX.

## Requirement

We need to simplify/clarify the UX. In the new UX, a new location to store the profile can be added. The user is guided in a wizard-like dialog: 
1. select, if dm3 name should be claimed or an owned name should be used
2. The storage location is selected (this depends on the type selected from 1. (all the existing options are still supported)
3. The name is claimed/selected, and the profile can be deployed

If a new profile is deployed, this also is in the list. Added profiles can be deleted (as it was now also available).

Another name/profile can be claimed/selected.

**IMPORTANT** the user is allowed to claim only one dm3 name (on each storage location, means 1 on cloud, 1 on optimism, ...). Is already one name is claimed, this option must be blocked.

Analogous is must be implemented for the smartphone view!

## Figma

see: https://www.figma.com/design/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?node-id=2218-2030

**IMPORTANT** The figma design is NOT complete. It shows only 1 path, but all paths must be implemented.

## Tasks

- [ ] Implementation new config dialog for web
- [ ] Implementation new config dialog for responsive design
- [ ] Testing of all paths
