### ISSUE TITLE
REQ: Property Dialog - Network

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#1128]
NEW Page!

## Reqirements

Create a property page to configure the delivery service nodes. The user can add a new node by giving the ENS name of the node. It must be checked, if the node exists (ENS name has the profile, and the node answers). When adding the node, it needs to be checked, if the user can create a profile there. If the node asks for onboarding, the user must be redirected to a page from the node.
Adding also means, that all published profiles need to be updated. Here the user needs to be informed. The process (for now) may have a bad user experience because several transactions on different chains need to be executed.

## Figma

https://www.figma.com/design/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?node-id=2219-5767

## Tasks

- [ ] Add page to property dialog
- [ ] Add page to responsive design
- [ ] Add function to delivery service API to create a profile (if needed), (the current nodes don't have restrictions)
