### ISSUE TITLE
EPIC: Responsive Design

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#700]
## Current situation

The UI components are only working for desktop browser size. Smartphone view is not useable. There is a responsiveness but adjustment for smartphone view is not yet realized.

## Requirement

The design must fit for different view types. (desktop, smartphone)

## Tasks

- [ ] Add smartphone view (according figma) for Conversation List
- [ ] Add smartphone view (according figma) for Message view
- [ ] Add smartphone view (according figma) for Menu
- [ ] Add smartphone view (according figma) for Properties Overlay

## Resources

Figma: 

- https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=1403-70&mode=design
- https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=1469-648&mode=design
- https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=1476-1183&mode=design
