### ISSUE TITLE
EPIC: New Properties Dialog

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#703]
## Current situation

The property dialog is still empty, and the profile configuration is separate. Not all configurations are available.

## Requirements 

Build a new (extended) dialog that will host all existing configurations and future ones as well

## Tasks

- [x] Build base dialog (with categories list and screens for each category
- [x] Build it for smartphones as well (defined later -> Prio3)
- [x] integrate existing profile configuration (see #705 )
- [x] add "General properties"
- [x] add "Spam protection"
- [x] add "Notifications"
- [x] add "Network" settings
- [x] add "Storage" settings
- [x] add "Information" page

## Resources

Figma:
https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=85-2774&mode=design
