### ISSUE TITLE
Add multichain handling in "config profile" dialog

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#705]
## Current behavior
The config profile dialog allows the user to define where his profile is published (address, dm3 user name, ens name). Other chains are not supported.

## Requirement
Instead of ENS only, other chains and naming systems must be supported for publishing the profile. A dropdown menu box needs to be added that allows the users to select the position to publish (see Figma). The preselection should always depend on the chain the user has selected in the wallet (metamask). For instance: if Ethereum is selected, "Ethereum Network - ENS" should be selected, if Gnosis is selected, "Gnosis Network - Genome" is selected. This list will be extended in the future. If the user selects another than the current network, the network change must be executed, when the publish button is pressed.
There can potentially be different Services on the same network (for instance "Ethereum - ENS and Ethereum - Unstoppable Domains"). The selection defines, which "write" method needs to be used.

The ENS/GNO name section of the dialog must be modular because other networks/chains will be added. The text might change slightly. The logic is the same. The extension to other networks must be easy without many changes (if at all) in the code. As the UI elements remain the same, only the texts and called methods might be switched.

## Tasks

- [x] add dropdown box to select the network and name/identity service
- [x] add different text templates for each network
- [x] add network selection enforcement when publishing
- [x] add modular network template (easy to extend with other networks
- [x] add ETH/ENS and GNOSIS/GNO
- [x] add auto-selection of the network

## Resources

Figma: https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=85-2774&mode=design
