### ISSUE TITLE
EPIC: Notifications

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#721]
## Background

Notifications (receiving a message) are essential for a reasonable user experience. The user should be able to select what notification he/she wants to have.

## Requirements

A framework must be implemented that enables notifications to be sent in various ways. The settings in the user interface must be easily configurable by the user. The notifications must be integrated into the delivery service so that the user can be informed when there is a message for them.

## Tasks

- [ ] the notification lib framework
- [ ] UI (prop-dialog, ...)
- [ ] Notification Backend (init, ...)
- [ ] email Notification 
- [ ] SMS Notification
- [ ] Push Notification (Browser)
- [ ] Web3 Notification Protocols
