### ISSUE TITLE
CHANGE: Attachment handling according specification (change)

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#793]
## Current situation

Attachments are added as an array of URIs as defined in the first version of the spec. This makes problems when adding files to the message as the file name gets lost.

## Requirements

Change the array of strings (URIs) into an array of attachment structs which contains a name entry and a data entry (containing the current URI).
The UI must use the name entry to store the file name to provide a convenient behavior for the user (name doesn't change).

## Tasks

- [x] Change API for Attachment handling
- [x] Change UI (messenger-widget) to handle file names correctly
- [x] Check storage definitions
- [x] Testing

## Resources

https://specification.dm3.network/base-protocol/message-transport-protocol-dm3mtp/message-transport#attachments
