### ISSUE TITLE
DM3MAP: Authentication at Delivery Service and Backand 

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#824]
## Current situation

Authentication is done by a SIWE like message/signature which is shared for the DS and backend (cloud storage)

## Requirement

To follow the DM3 specification (and vision), every user can be connected to various delivery services, the storage via cloud storage backend is optional and must not be coupled with any delivery service.

To log in to a service (delivery service, cloud storage service), the following message is passed signed with the signature key:
 
> ENS: [...]
> Address: [...]
> URI: https://dm3.chat/
> Version: 1
> Chain ID: 1
> Issued At: [...]
> Expiration Time: [...]
> Nonce: [...]

Additional to the standardized values:
`ENS` is the ENS name of the sender, `Address` is the sender's wallet address.

**The authentication process: (client side)**
1. Sign-in with wallet signature (SIWE-like Message) or interaction-free sign-in -> encryption and signing keys are derived/generated
2. Authentications for services are generated, signed with the signing key

**The authentication process: (service side)**
1. SIWE-like message and signature are received, 
2. Read the DM3 profile from the ens name (or from the reverse resolved address, if no ens name is given)
3. Check if a valid signature (signing key)

## Tasks

- [ ] Authentication mechanism (lib)
- [ ] Include in Delivery Service
- [ ] Include in Backend (Storage ...)
- [ ] Include in UI components

**Comment by malteish** [comment]
Notes

The user signs a message to connect their signing and encryption keys to their account: ![image](https://github.com/dm3-org/dm3/assets/102788938/49ca03f8-2208-49c9-a488-b32b4bb93daa)

sign up:
- login message -> create sig key
- publish profile
  - either on-chain with transaction
  - or off-chain with second signature: sign(profile, accountPrivateKey)
- sign profile and send to server -> create profile on server

sign in:
- login message -> sign with signature key (which is known from public records like ens or offchain)


sign(login, accountPrivateKey) -> entropy -> key derivation -> signatureKeyPrivateA -> sign(profile, ) -> signature -> zkp(signature, entropy, accountPublicKey)

Proof that the sender has access to `signature = sign(loginMessage, accountPrivateKey)`. `loginMessage` and `accountPrivateKey`, and `signature` must stay secret. 
Delivery service does not know loginMessage, and the backend does not always know it (e.g. if storage is not in backend).


Solutions
- for now: 2 signatures
- for later: make second signature obsolete with zkp

Think about later solution when implementing first step.

**Comment by malteish** [comment]
`submitUserProfile` is used both in backend and delivery service. It uses the signed `profileCreationMessage`, which is checked before a profile for the user is created with the service. Where should this actually happen?
Others need to query the user's profile from ens or an offchain resolver -> submitUserProfile is needed with those. Is this the task of the delivery service or the backend? Currently, both seem to store the profile and serve a route to access it.

see https://github.com/dm3-org/dm3/issues/907

**Comment by malteish** [comment]
Used this resource as a starter on how to use jwt: https://www.digitalocean.com/community/tutorials/nodejs-jwt-expressjs

**Comment by malteish** [comment]
Both backend and delivery service already issue their own challenges to the user for authentication, and verify these challenges are signed with the user's publicSigningKey.

**Comment by malteish** [comment]
Which information should be included in the jwt?
- ensName (user)
- expiration date (exp)
- issuance date (iat)
- do we need account? -> could theoretically change without invalidating the jwt

**Comment by malteish** [comment]
implemented except for the zk part
