### ISSUE TITLE
Frontend cleanup

### ISSUE THREAD

**Issue by AlexNi245** [dm3-org/dm3#887]
We've pushed a lot of new features during the last couple of months so it is a good time to do some cleanup before we continue with new developments. 

### Cleanup 
- [x] Go through the code and check if there are TODOS or comments.
- [x] Replace the old Global Context Provider with new hooks approach.
- [x] Remove the Config properties those are not used anymore.
- [x] Removal of the rainbowkit buttons: https://github.com/dm3-org/dm3/issues/893
- [x] Add links/content to the menu items like About : https://github.com/dm3-org/dm3/issues/894
- [x] Resize of DM3 logo on login screen : https://github.com/dm3-org/dm3/issues/895
- [x] Do some configuration so that app version automatically updates everywhere in widget whenever a new version is published.
- [x] Implement disconnect wallet feature in Preferences : https://github.com/dm3-org/dm3/issues/894
- [x] Modify the message action button style : https://github.com/dm3-org/dm3/issues/896
- [x] Breakdown the Message component into small parts for simplicity of understanding & code readability

### README
The README of the messenger-widget is currently empty. Add instructions on how to

- [x] Install the package from npm 
- [x] Include a section on how to add the widget to similar to steffens gist 
- [x] Add a section that explains every property the widget has and a short example how an example value could look like
- [x] add an example Props object
- [x] Cover how the widget can be used with next.js and vite
