### ISSUE TITLE
PERFORMANCE - At some points we need performance increase

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#898]
## Current Situation

At some points, the reference implementation is too slow.
- After sign-in --> "fetching contacts..." takes a very long time if many conversations exist
- "fetching contacts" also takes >6 seconds at first login (there are no conversations!), what else ar we doing?
- Switching conversation requires some waiting

## Requirements
There must be NO situation, where the user has to wait longer than 1 second.

## Tasks

- [ ] What can be cached
- [ ] Is something loaded that is not needed
- [ ] Load only, what is used/visualized. Load the rest in the background.
- [ ] If no conversations are shown (in the mode for one contact only), only read what is needed for this conversation!

**Comment by AlexNi245** [comment]
After profiling every component of the DM3 stack, I found two major issues we need to address to improve performance:

## Backend WebProvider Cache (Major)
Every web3 provider-related request is not cached, leading to a network call. This is particularly costly since every authenticated request requires at least one provider lookup to resolve the name. We need a cache for the Web3Provider. This cache should store every request to the web3Provider and invalidate old keys using the Least-Recently-Used strategy. Gashawk already has such a cache in place, so it might make sense to ask them if we could use it as well.

## Webserver (Major)
The larger limitation is the web server, which is heavily rate-limited and lacks some configurations necessary to serve requests properly. I have already significantly improved performance by:
- Easing up rate limiting to 20 requests
- Enabling gzip
- Enabling keep-alive option
The updated configuration has yet to merge though.

## HTTP 2 (Minor)
The web server does not support the latest HTTP 2 spec, which could further improve speed, especially when the client has to handle many small requests. It might make sense to add this feature.

## Pagination (Minor)
Sooner or later, we will need to implement pagination so the client can retrieve only the data it needs.

## Restructure API (Minor)
The API is rather arbitrary, leading to the client making multiple independent requests to render one element in the UI (e.g., preview message). It might make sense to tailor the API around the client's needs to reduce the number of requests.
